# Generated by Django 5.2.8 on 2026-03-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.CharField(max_length=100, unique=True)),
                ("json_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Summoner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tagline", models.CharField(max_length=100)),
                ("puuid", models.CharField(max_length=100, unique=True)),
                ("profile_icon_id", models.IntegerField(default=0)),
                ("profile_icon_url", models.URLField(blank=True, null=True)),
                ("level", models.IntegerField(default=1)),
                ("tier", models.CharField(default="Unranked", max_length=100)),
                ("rank", models.CharField(blank=True, max_length=10, null=True)),
                ("lp", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
