# Generated by Django 5.2.8 on 2026-03-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summoners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="match_id",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="summoner",
            name="puuid",
            field=models.CharField(db_index=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="summoner",
            name="rank",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
