# Generated by Django 5.2.8 on 2026-03-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summoners", "0002_alter_match_match_id_alter_summoner_puuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="json_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
