# Generated by Django 5.2.8 on 2026-03-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summoners", "0003_alter_match_json_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Champion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("champion_class", models.CharField(max_length=100)),
            ],
        ),
    ]
