# Generated by Django 5.2.8 on 2026-03-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summoners", "0004_champion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Augment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("tier", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("image_url", models.URLField()),
            ],
        ),
    ]
