# Generated by Django 5.2.8 on 2026-03-30 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summoners", "0005_augment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChampionAugmentRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.CharField(max_length=50)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "augment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="champion_ratings",
                        to="summoners.augment",
                    ),
                ),
                (
                    "champion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="augment_ratings",
                        to="summoners.champion",
                    ),
                ),
            ],
        ),
    ]
