# Generated by Django 5.2.8 on 2026-03-30 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summoners", "0006_championaugmentrating"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChampionAugmentCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.CharField(max_length=50)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "augments",
                    models.ManyToManyField(
                        related_name="synergy_cards", to="summoners.augment"
                    ),
                ),
                (
                    "champion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synergy_cards",
                        to="summoners.champion",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ChampionAugmentRating",
        ),
    ]
