# Generated by Django 5.2.8 on 2026-03-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summoners", "0008_championaugmentrating_delete_championaugmentcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="mvp_puuid",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
